name: molegent
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - openbabel=3.1.1
  - pip=21
  - python=3.7
  - rdkit=2021.03.5
  - ase
  - pip:
    - numpy
    - sklearn
    - cython==0.29
    - joblib
    - molsets==0.3.1
    - names==0.3.0
    - pyyaml==5.4.1
    - tensorboard==2.6.0
    - tqdm==4.62.3

